[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
slp = "88GS45m28ostoHorQLrQmTw2u9pU5hhRt8seHtdnByg2"

[programs.devnet]
slp = "88GS45m28ostoHorQLrQmTw2u9pU5hhRt8seHtdnByg2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/slp-deployer.json"

[scripts]
test = "cargo test"
